const newRegData = [
        {
            id: 'ASP0001',
            date: "2024-10-17",
            dob: "2003-11-07",
            fullName: "Subash Chandrabose",
            firstName: "Subash",
            lastName: "Chandrabose",
            email: "subash@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/subashchandrabose/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "Full-Time",
            status: "Access Granted",
          },
          {
            id: 'ASP0002',
            date: "2024-04-17",
            dob: "2005-01-07",
            fullName: "nihala tazeen",
            firstName: "nihala",
            lastName: "tazeen",
            email: "nihala@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/nihalatazeen/",
            mode: "Part-Time",
            session: "Afternoon",
            systemFacility: "No",
            currentlyStudying: "Yes",
            mode: "Remote",
            session: "Full-Time",
            status: "Access Granted",
          },
          {
            id: 'ASP0003',
            date: "2024-10-08",
            dob: "2004-11-08",
            fullName: "S.MOHAMMED UMAR",
            firstName: "S.MOHAMMED",
            lastName: "UMAR",
            email: "s.mohammedumar@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/smohammedumar/",
            mode: "Part-Time",
            session: "Evening",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "Remote",
            session: "Part-Time",
            status: "On Hold",
          },
          {
            id: 'ASP0004',
            date: "2024-03-11",
            dob: "2006-01-01",
            fullName: "noorunisha afrin",
            firstName: "noorunisha",
            lastName: "afrin",
            email: "noorunisha@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/noorunishaafrin/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0005',
            date: "2024-03-11",
            dob: "2003-01-01",
            fullName: "MUNAZA SADAF",
            firstName: "MUNAZA",
            lastName: "SADAF",
            email: "munaza@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/munazasadaf/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0006',
            date: "2024-03-11",
            dob: "2002-01-01",
            fullName: "Siqua Kulsum J",
            firstName: "Siqua",
            lastName: "Kulsum J",
            email: "siqua@gmail.com",
            mobile: "7256012036",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/siquakulsumj/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0007',
            date: "2024-08-10",
            dob: "2004-01-00",
            fullName: "Asma Anjum",
            firstName: "Asma",
            lastName: "Anjum",
            email: "asma@gmail.com",
            mobile: "8942568523",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/asmaanjum/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0008',
            date: "2024-09-10",
            dob: "2005-01-01",
            fullName: "Aisha Sultana",
            firstName: "Aisha",
            lastName: "Sultana",
            email: "aisha@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/aishasultana/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0009',
            date: "2024-10-10",
            dob: "2006-01-01",
            fullName: "Arifa Sultana",
            firstName: "Arifa",
            lastName: "Sultana",
            email: "arifa@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/arifasultana/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0010',
            date: "2024-11-10",
            dob: "2007-01-01",
            fullName: "Sana Sultana",
            firstName: "Sana",
            lastName: "Sultana",
            email: "sana@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/sanasultana/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0011',
            date: "2024-12-10",
            dob: "2008-01-01",
            fullName: "Nusrat Jahan",
            firstName: "Nusrat",
            lastName: "Jahan",
            email: "nusrat@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/nusratjahan/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0012',
            date: "2025-01-10",
            dob: "2009-01-01",
            fullName: "Rahul Kumar",
            firstName: "Rahul",
            lastName: "Kumar",
            email: "rahul@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/rahulkumar/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0013',
            date: "2025-02-10",
            dob: "2010-01-01",
            fullName: "Sourav Kumar",
            firstName: "Sourav",
            lastName: "Kumar",
            email: "sourav@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/souravkumar/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0014',
            date: "2025-03-10",
            dob: "2011-01-01",
            fullName: "Sayan Dey",
            firstName: "Sayan",
            lastName: "Dey",
            email: "sayan@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/sayandey/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0015',
            date: "2025-04-10",
            dob: "2012-01-01",
            fullName: "Ayush Kumar",
            firstName: "Ayush",
            lastName: "Kumar",
            email: "ayush@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/ayushkumar/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
          {
            id: 'ASP0016',
            date: "2025-05-10",
            dob: "2013-01-01",
            fullName: "Pratik Kumar",
            firstName: "Pratik",
            lastName: "Kumar",
            email: "pratik@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/pratikumar/",
            mode: "Full-Time",
            session: "Morning",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            session: "-",
            status: "Access Granted",
          },
    ]
    export default newRegData;