const newRegData = [
        {
            id: 'ASP0001',
            date: "2024-10-17",
            dob: "2003-11-07",
            fullName: "Subash Chandrabose",
            firstName: "Subash",
            lastName: "Chandrabose",
            email: "subash@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/subashchandrabose/",
            session: "Full-Time",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            status: "Access Granted",
          },
          {
            id: 'ASP0002',
            date: "2024-04-17",
            dob: "2005-01-07",
            fullName: "nihala tazeen",
            firstName: "nihala",
            lastName: "tazeen",
            email: "nihala@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/nihalatazeen/",
            session: "Part-Time",
            systemFacility: "No",
            currentlyStudying: "Yes",
            mode: "Remote",
            status: "Access Granted",
          },
          {
            id: 'ASP0003',
            date: "2024-10-08",
            dob: "2004-11-08",
            fullName: "S.MOHAMMED UMAR",
            firstName: "S.MOHAMMED",
            lastName: "UMAR",
            email: "s.mohammedumar@gmail.com",
            mobile: "1234567890",
            gender: "Male",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/smohammedumar/",
            session: "Part-Time",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "Remote",
            status: "On Hold",
          },
          {
            id: 'ASP0004',
            date: "2024-03-11",
            dob: "2006-01-01",
            fullName: "noorunisha afrin",
            firstName: "noorunisha",
            lastName: "afrin",
            email: "noorunisha@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/noorunishaafrin/",
            session: "Full-Time",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            status: "Access Granted",
          },
          {
            id: 'ASP0005',
            date: "2024-03-11",
            dob: "2003-01-01",
            fullName: "MUNAZA SADAF",
            firstName: "MUNAZA",
            lastName: "SADAF",
            email: "munaza@gmail.com",
            mobile: "1234567890",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/munazasadaf/",
            session: "Full-Time",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            status: "Access Granted",
          },
          {
            id: 'ASP0006',
            date: "2024-03-11",
            dob: "2002-01-01",
            fullName: "Siqua Kulsum J",
            firstName: "Siqua",
            lastName: "Kulsum J",
            email: "siqua@gmail.com",
            mobile: "7256012036",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/siquakulsumj/",
            session: "Full-Time",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            status: "Access Granted",
          },
          {
            id: 'ASP0007',
            date: "2024-08-10",
            dob: "2004-01-00",
            fullName: "Asma Fathima",
            firstName: "Asma",
            lastName: "Fathima",
            email: "asma@gmail.com",
            mobile: "8942568523",
            gender: "Female",
            techStack: "Basic Web Technology",
            degree: "Btech",
            linkedin: "https://www.linkedin.com/in/asmafathima/",
            session: "Full-Time",
            systemFacility: "Yes",
            currentlyStudying: "Yes",
            mode: "On-site",
            status: "Access Granted",
          },
          

         
    ]
    export default newRegData;